[package]

name = "ids_container"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Container which automatically assigns keys when you insert in it"
repository = "https://github.com/tomaka/rust-ids-container"
license = "Apache-2.0"
